# Generated by Django 3.2.24 on 2024-03-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_movie_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='movie_data',
            new_name='movie',
        ),
    ]
