# Generated by Django 3.2.24 on 2024-03-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_movie_data_post_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='movie',
            field=models.TextField(blank=True, default=''),
        ),
    ]
