# Generated by Django 3.2.24 on 2024-03-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='selected_movie',
            field=models.TextField(blank=True),
        ),
    ]
