# Generated by Django 3.2.24 on 2024-03-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_selected_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='selected_movie',
        ),
    ]
