# Generated by Django 3.2.24 on 2024-03-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_selected_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='movie',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
