# Generated by Django 3.2.24 on 2024-05-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_data', models.JSONField(blank=True, null=True)),
                ('user_rating', models.TextField(blank=True, default='[]')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
