# Generated by Django 3.2.24 on 2024-02-21 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie_type', models.CharField(choices=[('movie', 'movie'), ('series', 'series'), ('episode', 'episode')], max_length=10)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Western', 'Western'), ('Adventure', 'Adventure'), ('Science fiction', 'Science fiction'), ('Crime', 'Crime'), ('Animation', 'Animation'), ('Documentary', 'Documentary'), ('Mystery', 'Mystery'), ('History', 'History'), ('Sports', 'Sports'), ('Musical', 'Musical'), ('News', 'News')], max_length=15)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('directors', models.CharField(blank=True, max_length=255, null=True)),
                ('writers', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('countries', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_posters', models.URLField(blank=True, null=True)),
                ('plot_summary', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('box_office_results', models.CharField(blank=True, max_length=255, null=True)),
                ('production_company', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
