# Generated by Django 3.2.24 on 2024-02-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='box_office_results',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_posters',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_type',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='plot_summary',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_company',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='writers',
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='../default_profile_qdjgyp', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
