# Generated by Django 3.2.24 on 2024-05-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20240430_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_data',
            field=models.JSONField(blank=True, default='null'),
            preserve_default=False,
        ),
    ]
