# Generated by Django 3.2.24 on 2024-05-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_movie_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
