# Generated by Django 3.2.24 on 2024-05-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_user_ratings_movie_user_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='user_rating',
            new_name='user_ratings',
        ),
    ]
