# Generated by Django 3.2.24 on 2024-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20240220_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Western', 'Western'), ('Adventure', 'Adventure'), ('Science fiction', 'Science fiction'), ('Crime', 'Crime'), ('Animation', 'Animation'), ('Documentary', 'Documentary'), ('Mystery', 'Mystery'), ('History', 'History'), ('Sports', 'Sports'), ('Musical', 'Musical'), ('News', 'News')], max_length=15),
        ),
    ]
