# Generated by Django 3.2.24 on 2024-02-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20240222_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
