# Generated by Django 3.2.24 on 2024-05-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
