# Generated by Django 3.2.24 on 2024-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
